apiVersion: v1
kind: Service
metadata:
  name: multi-app-backend
spec:
  selector:
    app: multi-app-backend
  ports:
    - protocol: TCP
      port: 80        # Der Port, auf dem der Service erreichbar ist
      targetPort: 8080  # Der Port im Backend-Container (falls dein Backend auf einem anderen Port läuft, z. B. 3000, ändere diesen Wert)
  type: ClusterIP       # Interner Service (kein LoadBalancer notwendig)
