apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meine-website-ingress
spec:
  ingressClassName: nginx  # Verweist auf den NGINX Ingress-Controller
  rules:
    - host: www.multi-application.de  # Der Hostname, unter dem die Anwendung erreichbar ist
      http:
        paths:
          - path: /  # Der Pfad, unter dem die Anwendung erreichbar ist
            pathType: Prefix
            backend:
              service:
                name: multi-frontend  # Der Service, der die Anfragen verarbeiten soll
                port:
                  number: 80  # Der Port des Services